### ISSUE TITLE
with crypto? (Example with cryptocurrency pair)

### ISSUE THREAD

**Issue by tai-euler** [alberduris/SirajsCodingChallenges#1]
nice predictions are very close to reality! Can you do this with cryptocurrencies too?

**Comment by alberduris** [comment]
Sure! In fact it could be done with the exact same model as used for EUR/USD.

The only thing that is needed to be changed is the data input :)

If you are interested, please let me know and I'll upload another Jupyter Notebook with an example for a Cryptocurrency of your choice 👍

**Comment by pumaweb02** [comment]
I'm Also interested to see this code in crypto. Buen trabajo Alberto! 
Im Sending you an email.

**Comment by alberduris** [comment]
I'm glad to hear that @pumaweb02 💃 

Now uploading a new folder called "Crypto" with the same model but using data from BTC/USD. With data from Feb 02, 2012 until today 🚀 

Hope you find it useful!

Update: https://github.com/alberduris/SirajsCodingChallenges/tree/master/Stock%20Market%20Prediction/Crypto

**Comment by tai-euler** [comment]
nice thank you very much! If you have some spare time, could you do a 1-3 min intro about this code in a youtube video just to see how to use it correctly and predict markets?

**Comment by alberduris** [comment]
I'm not very confident about video.making but I'll think about it. Anyways, thank you very much for the suggestion @tai-euler.

Now I'm closing the Issue as the original topic (Crypto example) seems to be solved. 

Of course, everyone, feel free to open any other "Issue" for whatever.

**Comment by L4stH0pe** [comment]
Hello dude, I was playing with your code and its amazing, but i have a question, i was trying with some formulas to get the REAL PRICE, about to DEnormalize the predictions. can you help me with a some tip? thank you!

**Comment by alberduris** [comment]
Hi @L4stH0pe 

Thanks! And I think that this code should do the trick for you :)

[https://github.com/alberduris/stackoverflow/blob/master/standardize_destandardize/Standardize-Destandardize.ipynb](https://github.com/alberduris/stackoverflow/blob/master/standardize_destandardize/Standardize-Destandardize.ipynb)
