### ISSUE TITLE
csv data source

### ISSUE THREAD

**Issue by laclance** [alberduris/SirajsCodingChallenges#2]
Thank you so much for this code, may I ask where do you get the btcusd csv data?

**Comment by alberduris** [comment]
You're welcome.

Of course, it's from the historical data service of Investing.

Link: https://www.investing.com/currencies/btc-usd-historical-data

Just need to select start and end data and click on "Download". Some preprocessing may be needed ;)

![image](https://user-images.githubusercontent.com/7073086/31315806-1aea676a-ac20-11e7-900f-f99aaed39b1b.png)

**Comment by laclance** [comment]
great thank you kindly, using your code to help with my trading bot, will share when working well :)
