### ISSUE TITLE
PREGUNTA!

### ISSUE THREAD

**Issue by ghost** [alberduris/SirajsCodingChallenges#3]
Los datos que usas para probar la RNN están también en los datos de entrenamiento ???!!

**Comment by alberduris** [comment]
No, están en el archivo CSV, pero antes de comenzar el entrenamiento se realiza una partición _train/test_ para no testear con datos vistos en el entrenamiento :)

**Comment by ghost** [comment]
Pero por lo que veo el **datasetTest** esta contenido en el **datasetTrain**. El test esta formado por los **ultimos 101** puntos del **datasetTrain**

![capture](https://user-images.githubusercontent.com/13348358/31321206-4c747e6c-ac82-11e7-9e89-0f07ba910d25.JPG)

**Comment by alberduris** [comment]
Efectivamente, es un fallo del que no tenía constancia. Bueno, la idea es la primera y para conseguirlo sólo habría que modificar ligeramente la línea de asignación a **datasetTrain**.

Si quieres modificarlo y hacer un PR lo revisaré y aceptaré ^^
